### ISSUE TITLE
A student cannot apply for a thesis.

### ISSUE THREAD

**Issue by vkarakolis-epu** [QualiChain/fe#373]

**Comment by mmilaprat** [comment]
can you provide more information about this issue? A student can apply to a thesis, he cannot when he has been asigned to another thesis.

**Comment by sskalidakis** [comment]
There should be a message for the users informing them about that. And probably a link to that thesis object .

**Comment by mmilaprat** [comment]
into the thesis main page and into the profile page there is the list of thesis per user with the status. But I'll add also a message that advice user if he has a thesis.
