### ISSUE TITLE
Recruiter should not have recommended jobs, courses, skills and job applications to his profile page

### ISSUE THREAD

**Issue by vkarakolis-epu** [QualiChain/fe#377]

**Comment by mmilaprat** [comment]
please remove them from the user permisions

example:

"get_job_recommendations": [
    "student", 
    "recruiter", 
    "life long learner", 
    "employee", 
    "job seeker", 
    "administrator"
  ],

**Comment by vkarakolis-epu** [comment]
removed the permissions, will be deployed these days
