### ISSUE TITLE
Competency development and skill recommendations not useful for professors

### ISSUE THREAD

**Issue by vkarakolis-epu** [QualiChain/fe#379]

**Comment by mmilaprat** [comment]
related with skills, plese update user_permissions, now is:

"get_skills_recomendations": [
    "student", 
    "professor", 
    "recruiter", 
    "life long learner", 
    "employee", 
    "job seeker", 
    "administrator"
  ], 

related with Competency development, is solved in the current FE version in GIT

**Comment by vkarakolis-epu** [comment]
updated permissions, will be deployed these days
