### ISSUE TITLE
Invalid credentials when logging in with a newly created user

### ISSUE THREAD

**Issue by sskalidakis** [QualiChain/fe#387]
I registered a new user from the heroku app and tried to log in to the platform. I was given a message of "Invalid credentials". Checking the requests I saw that this one failed.
http://qualichain.epu.ntua.gr:5004/users/IAM-6089617a48a2270024ff685a
This API needs the id of the Qualichain DB **not the IAM MongoDB id** .

@RafaelAPB  and @mmilaprat could you check that?

**Comment by mmilaprat** [comment]
FE expects the QC user id from the IAM auth API, at this moment the IAM auth API doen't return this value for new users. As far I know NTUA and INESC-ID are working on it.
