### ISSUE TITLE
When a recruiter views a job in the jobs section, two API calls fail

### ISSUE THREAD

**Issue by sskalidakis** [QualiChain/fe#395]
When a recruiter views a job in the jobs section, two API calls fail: 

GET http://knowledgebizvpn.ddns.net:8000/cv/19 400 (Bad Request)
GET http://knowledgebizvpn.ddns.net:8000/profiles/19/applications 400 (Bad Request)

@mmilaprat and @mehrbodKBZ could you check that?

**Comment by mmilaprat** [comment]
Is the response of these APIs when ther was no data for a user. But as in this case the user is a recruiter, it not make sense that use these API calls to try to recover data. I'm going to update FE to avoid to use these calls if user is not employee or student.

**Comment by mmilaprat** [comment]
can we close this issue?
