### ISSUE TITLE
Job list in the Recruitment section misses newly created jobs

### ISSUE THREAD

**Issue by sskalidakis** [QualiChain/fe#396]
It seems that newly created jobs by a recruiter are not present in that list. (thus the job applications for new jobs cannot be handled by a recruiter) Not sure if this is an API issue or a FE issue. Could you check that?

**Comment by mmilaprat** [comment]
yesterday I send an email, there was a bug after change the way to store creator_id of jobs, the FE code has been updated and it needs to be redelployed

**Comment by sskalidakis** [comment]
Sorry, I missed that one. I will redeploy the new version as soon as possible.
