### ISSUE TITLE
CV update is not working

### ISSUE THREAD

**Issue by vkarakolis-epu** [QualiChain/fe#405]
For the user student@tecnico.ulisboa.pt, update skills of CV is not working.
Specifically I am deleting the skill blockchain but I still see this skill to the list of skills.
Also, if I add a skill (e.g. Java) it is not included in the list of skills.
@mmilaprat, @mehrbodKBZ could you please have  a look?

**Comment by mmilaprat** [comment]
it worked few days ago, @mehrbodKBZ the API has been changed? it doesn't return any error

I was able to add/edt skills ussing the competency development functionality

cv/<userId>/skills

but with the "/cv" not

**Comment by mmilaprat** [comment]
Can we close this issue?

**Comment by mehrbodKBZ** [comment]
I think so. 
Just do not know if the last version of FE is already deployed?

**Comment by vkarakolis-epu** [comment]
@mehrbodKBZ The FE was lastly deployed on Friday around 12.30 CET
